services:
  db:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: wobot
      POSTGRES_PASSWORD: example
      POSTGRES_DB: wobot_db
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - wobot_network

  wobot:
    build: .
    image: wobot
    restart: unless-stopped
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://wobot:example@db:5432/wobot_db
    env_file:
      - .env
    volumes:
      - ./assets:/assets
    networks:
      - wobot_network

networks:
  wobot_network:
    driver: bridge
